---
- name: Deploy code on servers
  hosts: "{{myHosts}}"
  become: yes
  remote_user: root
  become_user: root

  tasks:

    - name: Creates directory
      file:
        path: .aws
        state: directory

    - name: Copy aws creds
      template:
        src: aws.creds.j2
        dest: ~/.aws/credentials

    - name: Copy docker compose file
      copy:
        src: "{{compose_file}}"
        dest: /opt/webapps/
        mode: 0755

    - name: ecr docker get-authorization-token
      shell: "aws ecr get-authorization-token  \
      --profile default --region eu-west-2"
      register: ecr_command

    - set_fact:
        ecr_authorization_data: "{{ (ecr_command.stdout | from_json).authorizationData[0] }}"

    - set_fact:
        ecr_credentials: "{{ (ecr_authorization_data.authorizationToken | b64decode).split(':') }}"


    - name: docker_repository - Log into ECR registry and force re-authorization
      docker_login:
        registry_url: 335871625378.dkr.ecr.eu-west-2.amazonaws.com/rekeyole-app:latest
        username: "{{ ecr_credentials[0] }}"
        password: "{{ ecr_credentials[1] }}"
        reauthorize: yes

    - name: Docker Compose down
      ansible.builtin.shell: docker-compose down
      args:
        chdir: /opt/webapps/


    - name: Docker compose up
      ansible.builtin.shell: docker-compose pull && docker-compose up -d
      args:
        chdir: /opt/webapps/

    - name: Log out of DockerHub
      docker_login:
        registry_url: 335871625378.dkr.ecr.eu-west-2.amazonaws.com/rekeyole-app:latest
        state: absent

    - name: Delete content & directory
      file:
        state: absent
        path: ~/.aws/credentials